Images = {
  TILES: 'tiles'
  TILES_DATA: '../images/tiles_small.png'

  PORTAL: 'portal'
  PORTAL_DATA: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAEgCAYAAA
DVDXFAAAABe0lEQVR4Xu3dQRLBMBgG0DqCK9i5kOPIpMdxITtXcASmpR2ihC
hq5lkhzZ/PkzTdZVYVvmKMh8uuIYRZSam2U1qspFBJnya0AAQI3Agsw7pdUf
uSdfWgz/zcto11f9XgMpxsgN2LIovk+rcFBJicQBoo/c8/PgcEIDCqQHPT2l
SHq2e8dC9IBywN0N0gV9Xpaax/kBSAAAECBAgQIECAAAECBAgQIECAAAECBA
gQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBA
gQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBA
gQIECAAAECBAgQIECAAAECBAgQIECAAIGfCsQY+zPPl2HdHk3+qXPPt7Hujj
6vQginw88FIPCXAv1UvvNmkXw/P38ebRUI8HWB3IC59rfnQG6AXPvTAXKFxm
wf3AvGHCBXSwAC0xHIzdah9ssdtGlvfk1JnSMv4vF75/xKqwAAAABJRU5Erk
Jggg=='

  P1: 'player1'
  P1_DATA: '../images/playerNew1.png'

  P2: 'player2'
  P2_DATA: '../images/playerNew2.png'
}

Loader.loadImage(Images.TILES, Images.TILES_DATA)
Loader.loadImage(Images.PORTAL, Images.PORTAL_DATA)
Loader.loadImage(Images.P1, Images.P1_DATA)
Loader.loadImage(Images.P2, Images.P2_DATA)
